FROM python:3.7-alpine3.8
WORKDIR /app
RUN apk --update add --no-cache libjpeg \
                                jpeg-dev \
                                tiff-dev \
                                lcms2-dev \
                                libpq \
                                libwebp-dev \
                                libxml2-dev \
                                libxslt-dev \
                                postgresql-dev \
                                musl-dev \
                                gettext \
                                git \
                                gcc \
                                musl-dev \
                                zlib-dev \
                                tk-dev \
                                tcl-dev \
                                libffi-dev \
                                libmagic \
                                postgresql-client \
                                py-cffi

COPY requirements/ requirements/
RUN pip install --upgrade pip
RUN pip install -r ./requirements/local.txt --src=/root/pip
COPY docker/app/wait-for.sh /usr/local/bin/wait-for
COPY docker/app/start-flower.sh /usr/local/bin/start-flower
