# Generated by Django 2.2.10 on 2020-03-11 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0009_modify_profile_birth_date_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('password', models.CharField(blank=True, max_length=8)),
                ('initial_hp', models.PositiveSmallIntegerField(default=100)),
                ('questions_limit', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='questions.QuestionGroup')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=255)),
                ('hp', models.PositiveSmallIntegerField(default=100)),
                ('right_answers_count', models.PositiveSmallIntegerField(default=0)),
                ('current_question_number', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.Game')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_answers', to='questions.Answer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.Player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_answers', to='questions.Question')),
            ],
        ),
    ]
