# Generated by Django 2.2 on 2019-10-01 09:29

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='file',
            field=models.ImageField(upload_to=files.models.get_file_upload_path),
        ),
    ]
