# Generated by Django 2.2.6 on 2019-10-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_is_verified_field'),
        ('users', '0007_add_avatar_field'),
    ]

    operations = [
    ]
