# Generated by Django 2.2.6 on 2019-11-04 07:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20191030_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1910, 1, 1)), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Date of birth'),
        ),
    ]
